apiVersion: v1
kind: Pod
metadata:
  name: chani
  labels:
    name: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    project: roboshop
  tolerations:
  - key: "squad"
    operator: "Equal"
    value: "telsa"
    effect: "NoExecute"