apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  labels:
    project: roboshop
    envieonment: dev
spec:
  containers:
  - name: frontend
    image: nginx 
    envFrom:
    - secretRef:
        name: mysecret
        