# spot-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: super-cluster
  region: us-east-1

managedNodeGroups:
- name: spot
  instanceType: t3.micro
  spot: true
  desiredCapacity: 2