apiVersion: v1 
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    project: roboshop
    application: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    application: frontend
  ports:
  - port: 27017
    targetPort: 27107