apiVersion: v2 #The chart API version (required)
name: nginx #The name of the chart (required)
version: 1.0.0 #The version of the chart (required)
appVersion: 1.29.8 A SemVer range of compatible Kubernetes versions (optional)
description: upgrading to 1.29.8