
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::031277186300:role/eksctl-super-cluster-nodegroup-spo-NodeInstanceRole-eUFVJ8xC6UmJ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::031277186300:user/chanakya
      username: chanak
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-15T09:21:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1173"
  uid: 64fb3fa5-a6f1-4708-ad3f-c63d4fd96b4d
