apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::031277186300:role/eksctl-super-cluster-nodegroup-spo-NodeInstanceRole-Di0KnkTcCkAs
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::031277186300:user/chanakya
      username: chanakya
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::031277186300:user/chani
      username: chani
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-16T15:10:07Z"
  name: aws-auth
  namespace: kube-system
  uid: 776bed40-49d9-4145-bf74-4bf0d9189764