apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.deployment.name }}-{{ .Values.sevice.name }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
